### ISSUE TITLE
自动打卡测试失败

### ISSUE THREAD

**Issue by zyh778** [bean661/WoZaiXiaoYuanPuncher#1]
你好，我在最后测试的时候，调用失败，日志显示为这样是怎么回事啊

https://shared.lc-cn-n1-shared.com:443 "GET /1.1/classes/info_zhu?where=%7B%7D&limit=1 HTTP/1.1" 404 None

ERROR RequestId: ----------------- Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 229, in main_handler\n    wzxy = WoZaiXiaoYuanPuncher(config)\n  File \"/var/user/index.py\", line 61, in __init__\n    self.leanCloud_obj = leanCloud(self.leanCloud_data['appId'],self.leanCloud_data['masterKey'],self.leanCloud_data['class_name'])\n  File \"/var/user/index.py\", line 13, in __init__\n    self.obj = leancloud.Query(class_name).first()\n  File \"/var/user/leancloud/query.py\", line 210, in first\n    content = self._do_request(params)\n  File \"/var/user/leancloud/query.py\", line 197, in _do_request\n    \"/classes/{0}\".format(self._query_class._class_name), params\n  File \"/var/user/leancloud/client.py\", line 110, in new_func\n    return func(headers=headers, *args, **kwargs)\n  File \"/var/user/leancloud/client.py\", line 177, in new_func\n    content.get(\"code\", 1), content.get(\"error\", \"Unknown Error\")\nleancloud.errors.LeanCloudError: LeanCloudError: [101] Class or object doesn't exists.","statusCode":430}

**Comment by zyh778** [comment]
> 你好，我在最后测试的时候，调用失败，日志显示为这样是怎么回事啊 
> 
> https://shared.lc-cn-n1-shared.com:443 "GET /1.1/classes/info_zhu?where=%7B%7D&limit=1 HTTP/1.1" 404 None
> 
> ERROR RequestId:8fde0bb5-4590-4b34-8d9c-a7d926d4580f Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n File "/var/user/index.py", line 229, in main_handler\n wzxy = WoZaiXiaoYuanPuncher(config)\n File "/var/user/index.py", line 61, in **init**\n self.leanCloud_obj = leanCloud(self.leanCloud_data['appId'],self.leanCloud_data['masterKey'],self.leanCloud_data['class_name'])\n File "/var/user/index.py", line 13, in **init**\n self.obj = leancloud.Query(class_name).first()\n File "/var/user/leancloud/query.py", line 210, in first\n content = self._do_request(params)\n File "/var/user/leancloud/query.py", line 197, in _do_request\n "/classes/{0}".format(self._query_class._class_name), params\n File "/var/user/leancloud/client.py", line 110, in new_func\n return func(headers=headers, *args, **kwargs)\n File "/var/user/leancloud/client.py", line 177, in new_func\n content.get("code", 1), content.get("error", "Unknown Error")\nleancloud.errors.LeanCloudError: LeanCloudError: [101] Class or object doesn't exists.","statusCode":430}
>

**Comment by bean661** [comment]
先检查下leancloud依赖有没有安装成功，然后检查下leanCloud配置信息是否正确

**Comment by bean661** [comment]
如果还需要 可以加我QQ GitHub看的不及时

**Comment by bean661** [comment]
如果还需要 可以加我QQ 在简介， GitHub看的不及时
